name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Setup nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-21.11
        extra_nix_config: |
          # save space on disk and in cache
          auto-optimise-store = true
          # keep all store paths necessary to build the outputs
          keep-outputs = true
          keep-derivations = true

    - name: cache nix store
      id: cache-nix-store
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('**/shell.nix') }}
        path: |
          nix_store_dir
          nix_store_db.sqlite
    
    - name: restore cached nix store
      run: |
        if [ -e nix_store_db.sqlite ]; then
          sudo systemctl stop nix-daemon
          # put cached store paths back in their proper locations
          sudo rm -rf /nix/store /nix/var/nix/db/db.sqlite
          sudo mv nix_store_dir /nix/store
          sudo cp nix_store_db.sqlite /nix/var/nix/db/db.sqlite
          # fix store permissions
          sudo chmod 1775 /nix/store
          sudo chown root:nixbld /nix/store
          sudo chmod 0644 /nix/var/nix/db/db.sqlite
          sudo chown -R root:root /nix/store /nix/var/nix/db/db.sqlite
          sudo systemctl start nix-daemon
        fi

    - name: nix-shell
      run: nix-shell

    - name: cargo build
      run: nix-shell && cargo build

    - name: cargo test
      run: nix-shell && cargo test

    - name: cargo clippy
      run: nix-shell && cargo clippy -- -D warnings

    - name: cargo fmt
      run: nix-shell && cargo fmt --check

    - name: prepare nix store for caching
      run: |
        sudo systemctl stop nix-daemon
        # move store to a place where the cache action can read it
        sudo mv /nix/store nix_store_dir
        sudo mv /nix/var/nix/db/db.sqlite nix_store_db.sqlite